Connected callback (before render) recipe
trailheadapps/visualforce-to-lwc pull request #172
Opened 2021-07-07 14:15 UTC by albarivas

### What does this PR do?
Adds a new recipe that compares action attribute with connectedCallback

### What issues does this PR fix or reference?

#<Insert GitHub Issue>

## The PR fulfills these requirements:

[x] Tests for the proposed changes have been added/updated.
[x] Code linting and formatting was performed.

### Functionality Before

<insert gif and/or summary>

### Functionality After

<insert gif and/or summary>

2021-07-15 08:37 UTC, pozil commented on force-app/main/default/classes/CreateRecordPrepopulatedController.cls-meta.xml
> +<ApexClass xmlns="urn:metadata.tooling.soap.sforce.com">
@albarivas I'm curious about this change: any idea about how this landed here?
Looking at other `.cls-meta.xml` files I created recently, I see the `http` version of the `xmlns` attribute.

2021-07-15 08:45 UTC, pozil approved these changes
Approved but see my comments on the `.cls-meta.xml` files.

2021-07-16 07:46 UTC, albarivas commented on force-app/main/default/classes/CreateRecordPrepopulatedController.cls-meta.xml
> +<ApexClass xmlns="urn:metadata.tooling.soap.sforce.com">
I found why: https://github.com/forcedotcom/cli/issues/173

I don't mind using one or the other though!

2021-07-28 09:29 UTC, adityanaag3 requested changes
Recipe looks good, but this component isn't currently added to any page. I guess #171 must be merged first, and then we add this component to the basics tab?

2021-08-11 16:04 UTC, adityanaag3 approved these changes

2021-08-11 16:14 UTC, merged